name = input("what is your name?")
dob = input('Enter date of Birth')
city = input('Enter city')
collage = input('Enter collage')
fav_food = input('Enter fav food')
fav_song = input('enter song')
fav_animal = input('Enter animal')
fav_movies = input('Enter the movies')
print(name, dob, city, collage, fav_food, fav_song, fav_animal, fav_movies)